### ISSUE TITLE
Module parse failed: Unexpected token (Loader)

### ISSUE THREAD

**Issue by fimbres** [contentful/live-preview#184]
Hey there, I'm just trying to use the live preview sdk in a Harmony/Nucleus app (which uses react to create user interfaces in the frontend) but when I start the app it throws the following error:

```
ERROR  Failed to compile with 1 errors                                                                   1:35:47 PM

 error  in ./node_modules/@contentful/live-preview/dist/index-8836099c.js

Module parse failed: Unexpected token (31:81)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }) {
|   var s, o;
>   t[i] = ((o = (s = e.fields) == null ? void 0 : s[i]) == null ? void 0 : o[n]) ?? null;
| }
| function H(t) {

 @ ./node_modules/@contentful/live-preview/dist/react.js 3:0-54 712:2-3 720:64-66 723:13-14 736:48-49
 @ ./src/App.js
 @ ./src/client.js

[
  ModuleParseError: Module parse failed: Unexpected token (31:81)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | }) {
  |   var s, o;
  >   t[i] = ((o = (s = e.fields) == null ? void 0 : s[i]) == null ? void 0 : o[n]) ?? null;
  | }
  | function H(t) {
      at handleParseError (/Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/webpack/lib/NormalModule.js:469:19)
      at /Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/webpack/lib/NormalModule.js:503:5
      at /Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/webpack/lib/NormalModule.js:358:12
      at /Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/loader-runner/lib/LoaderRunner.js:373:3
      at iterateNormalLoaders (/Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
      at /Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/loader-runner/lib/LoaderRunner.js:205:4
      at /Users/P558DDP/Documents/ocm_pd_experience_content-preview/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
]
Webpack Build Time For Client Build:  835 ms
```

This are all the dependencies inside  package.json:
```
"devDependencies": {
    "@harmony/composer-experience": "^8.6.0",
    "@harmony-composer-plugin": "^5.26.2",
    "@nucleus/shell": "^32.0.0"
  },
  "dependencies": {
    "@apollo/react-ssr": "^4.0.0",
    "@contentful/live-preview": "^2.4.3",
    "classnames": "^2.3.2",
    "core-js": "2.6.11",
    "prop-types": "^15.8.1",
    "react": "^17.0.2"
  },
```

Is there any other dependencies such as loaders that I need to install in order to get this to work?

**Comment by z0al** [comment]
It looks like the Nullish Coalescing operator (`??`) is causing the issue. If you use Babel, you can add the [@babel/plugin-transform-nullish-coalescing-operator](https://babeljs.io/docs/babel-plugin-transform-nullish-coalescing-operator) plugin to your setup to unblock yourself.

I will check with the team if this is expected.

**Comment by fimbres** [comment]
Yes you are right @z0al, is there any already transpiled dist that works? So I can add it to the project

**Comment by YvesRijckaert** [comment]
Hi @fimbres this is expected behaviour, you can use [@babel/plugin-transform-nullish-coalescing-operator](https://babeljs.io/docs/babel-plugin-transform-nullish-coalescing-operator) to adjust your build process.
